# Generated by Django 2.2.3 on 2019-09-09 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='breed',
            new_name='genre',
        ),
    ]
