# Generated by Django 2.2.3 on 2019-09-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190911_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='chars',
            field=models.ManyToManyField(to='main_app.Char'),
        ),
    ]
